version: "3"
services:
  llm-answer-engine:
    build: .
    environment:
      - OPENAI_API_KEY=your_openai_api_key
      - GROQ_API_KEY=your_groq_api_key
      - BRAVE_SEARCH_API_KEY=your_brave_search_api_key
      - SERPER_API=your_serper_api_key
# uncomment the following the change the default config (ollama, etc)
#    volumes:
#      - $PWD/config.tsx:/home/node/app/config/config.tsx:ro
    ports:
      - 3000:3000
